name = "prism"
version = "0.1.0"
description = "Generate typesafe Gleam APIs from SQL"
licenses = ["Apache-2.0"]
repository = { type = "github", user = "anddani", repo = "prism" }
gleam = ">= 1.11.0"
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
argv = ">= 1.1.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 2.0.0 and < 3.0.0"
shellout = ">= 1.8.0 and < 2.0.0"
